name: Run Flask App

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Install Jupyter Notebook dependencies (if needed for check2.ipynb)
        run: |
          python -m pip install jupyter

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --execute --to notebook check2.ipynb

      - name: Create static folder (if it doesn't exist)
        run: |
          mkdir -p static  # Ensures static folder exists

      - name: Copy plot images to static folder
        run: |
          cp my_plot.png my_plot1.png static/

      - name: Overwrite index.html with generated version (if it exists)
        id: overwrite-index-html
        if: path.exists('check2.nbconvert.ipynb')  # Only run if file exists
        run: |
          mv check2.nbconvert.ipynb index.html

      - name: Download generated index.html (if uploaded)
        if: steps.overwrite-index-html.outputs == '1'  # Only download if uploaded
        uses: actions/download-artifact@v3
        with:
          name: index.html

      - name: Deploy Flask application (assuming basic deployment for demo)
        run: |
          if [[ -f index.html ]]; then
            cp index.html .  # Copy downloaded index.html to main directory
          fi
          python3 app.py &  # Start Flask app in background
          sleep 20          # Wait for app to start (adjust as needed)
