name: Run Flask App

on:
  push:


jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Install Jupyter Notebook dependencies (if needed for check2.ipynb)
        run: |
          python -m pip install jupyter
      - name: Run Jupyter Notebook (replace with script call if not using notebook)
        run: |
          jupyter notebook check2.ipynb
      - name: Run Flask application
        run: python3 app.py
